the keywords and main movie dataset are two different csv files but i will join them based on id to make things easier

In [303]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd
import numpy as np
import ast
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Set the path to the file you'd like to load
file_path = "movies_metadata.csv"

keywords_path = "keywords.csv"

df2 = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "rounakbanik/the-movies-dataset",
  keywords_path,
)


# Load the latest version
df1 = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "rounakbanik/the-movies-dataset",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)
df1['id'] = df1['id'].astype(str)
df2['id'] = df2['id'].astype(str)
df = pd.merge(df1, df2, on='id', how='inner')


print("First 5 records:", df.head())

First 5 records:    adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1  False                                                NaN  65000000
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3  False                                                NaN  16000000
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                     [{'id': 35, 'name': 'Comedy'}]

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en
1                                   NaN   8844  tt0113497                en
2                                   NaN  15602  tt0113228                en
3                                   NaN  31357  tt0114885                en
4                                   NaN  11862  tt0113041                en

                original_title  \
0                    Toy Story
1                      Jumanji
2             Grumpier Old Men
3            Waiting to Exhale
4  Father of the Bride Part II

                                            overview  ...      revenue  \
0  Led by Woody, Andy's toys live happily in his ...  ...  373554033.0
1  When siblings Judy and Peter discover an encha...  ...  262797249.0
2  A family wedding reignites the ancient feud be...  ...          0.0
3  Cheated on, mistreated and stepped on, the wom...  ...   81452156.0
4  Just when George Banks has recovered from his ...  ...   76578911.0

  runtime                                   spoken_languages    status  \
0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released
1   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released
2   101.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released
3   127.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released
4   106.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released

                                             tagline  \
0                                                NaN
1          Roll the dice and unleash the excitement!
2  Still Yelling. Still Fighting. Still Ready for...
3  Friends are the people who let you be yourself...
4  Just When His World Is Back To Normal... He's ...

                         title  video vote_average vote_count  \
0                    Toy Story  False          7.7     5415.0
1                      Jumanji  False          6.9     2413.0
2             Grumpier Old Men  False          6.5       92.0
3            Waiting to Exhale  False          6.1       34.0
4  Father of the Bride Part II  False          5.7      173.0

                                            keywords
0  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

[5 rows x 25 columns]

/Users/sanakulkarni/Datasets/Movie-Recommendation/venv/lib/python3.11/site-packages/kagglehub/pandas_datasets.py:92: DtypeWarning: Columns (0: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  result = read_function(

In [304]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46482 entries, 0 to 46481
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  46482 non-null  str
 1   belongs_to_collection  4557 non-null   str
 2   budget                 46482 non-null  str
 3   genres                 46482 non-null  str
 4   homepage               7986 non-null   str
 5   id                     46482 non-null  str
 6   imdb_id                46465 non-null  str
 7   original_language      46471 non-null  str
 8   original_title         46482 non-null  str
 9   overview               45487 non-null  str
 10  popularity             46478 non-null  object
 11  poster_path            46083 non-null  str
 12  production_companies   46478 non-null  str
 13  production_countries   46478 non-null  str
 14  release_date           46394 non-null  str
 15  revenue                46478 non-null  float64
 16  runtime                46214 non-null  float64
 17  spoken_languages       46478 non-null  str
 18  status                 46396 non-null  str
 19  tagline                20726 non-null  str
 20  title                  46478 non-null  str
 21  video                  46478 non-null  object
 22  vote_average           46478 non-null  float64
 23  vote_count             46478 non-null  float64
 24  keywords               46482 non-null  str
dtypes: float64(4), object(2), str(19)
memory usage: 8.9+ MB

In [305]:
df.insert(0, 'imdb_id', df.pop('imdb_id')) # rearrange the columns for better readability
df.insert(1, 'title',df.pop('title'))
df.insert(2, 'tagline',df.pop('tagline'))

In [306]:
unique_count = df['imdb_id'].nunique()

print(unique_count)

45415

In [307]:
# Filter for ALL rows where the ID is repeated
all_duplicates = df[df.duplicated(subset=['imdb_id'], keep=False)]

# Sort by 'user_id' so the matching ones are printed side-by-side
print(all_duplicates.sort_values(by='imdb_id').head())

         imdb_id                  title tagline  adult belongs_to_collection  \
36494  tt0009369                 Mickey     NaN  False                   NaN
36495  tt0009369                 Mickey     NaN  False                   NaN
36393  tt0011865  Why Change Your Wife?     NaN  False                   NaN
36392  tt0011865  Why Change Your Wife?     NaN  False                   NaN
36394  tt0012465         Miss Lulu Bett     NaN  False                   NaN

       budget                                             genres homepage  \
36494  250000  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...      NaN
36495  250000  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...      NaN
36393       0  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...      NaN
36392       0  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...      NaN
36394       0  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...      NaN

           id original_language  ...  \
36494   54242                en  ...
36495   54242                en  ...
36393   53766                en  ...
36392   53766                en  ...
36394  130275                en  ...

                                    production_countries release_date  \
36494  [{'iso_3166_1': 'US', 'name': 'United States o...   1918-08-01
36495  [{'iso_3166_1': 'US', 'name': 'United States o...   1918-08-01
36393  [{'iso_3166_1': 'US', 'name': 'United States o...   1920-05-21
36392  [{'iso_3166_1': 'US', 'name': 'United States o...   1920-05-21
36394  [{'iso_3166_1': 'US', 'name': 'United States o...   1921-11-01

         revenue runtime                          spoken_languages    status  \
36494  8000000.0    93.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
36495  8000000.0    93.0  [{'iso_639_1': 'en', 'name': 'English'}]  Released
36393        0.0    90.0                                        []  Released
36392        0.0    90.0                                        []  Released
36394        0.0    71.0                                        []  Released

       video  vote_average  vote_count  \
36494  False           7.5         4.0
36495  False           7.5         4.0
36393  False           7.5         2.0
36392  False           7.5         2.0
36394  False           5.0         1.0

                                                keywords
36494  [{'id': 242, 'name': 'new york'}, {'id': 13014...
36495  [{'id': 242, 'name': 'new york'}, {'id': 13014...
36393                                                 []
36392                                                 []
36394                                                 []

[5 rows x 25 columns]

In [308]:
df = df.drop_duplicates(subset=['id'], keep='first')

df.info()

<class 'pandas.DataFrame'>
Index: 45432 entries, 0 to 46481
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   imdb_id                45415 non-null  str
 1   title                  45429 non-null  str
 2   tagline                20401 non-null  str
 3   adult                  45432 non-null  str
 4   belongs_to_collection  4488 non-null   str
 5   budget                 45432 non-null  str
 6   genres                 45432 non-null  str
 7   homepage               7774 non-null   str
 8   id                     45432 non-null  str
 9   original_language      45421 non-null  str
 10  original_title         45432 non-null  str
 11  overview               44478 non-null  str
 12  popularity             45429 non-null  object
 13  poster_path            45046 non-null  str
 14  production_companies   45429 non-null  str
 15  production_countries   45429 non-null  str
 16  release_date           45345 non-null  str
 17  revenue                45429 non-null  float64
 18  runtime                45172 non-null  float64
 19  spoken_languages       45429 non-null  str
 20  status                 45348 non-null  str
 21  video                  45429 non-null  object
 22  vote_average           45429 non-null  float64
 23  vote_count             45429 non-null  float64
 24  keywords               45432 non-null  str
dtypes: float64(4), object(2), str(19)
memory usage: 9.0+ MB

In [309]:
df = df.drop_duplicates(subset=['imdb_id'], keep='first')

df.info()

<class 'pandas.DataFrame'>
Index: 45416 entries, 0 to 46481
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   imdb_id                45415 non-null  str
 1   title                  45413 non-null  str
 2   tagline                20398 non-null  str
 3   adult                  45416 non-null  str
 4   belongs_to_collection  4486 non-null   str
 5   budget                 45416 non-null  str
 6   genres                 45416 non-null  str
 7   homepage               7773 non-null   str
 8   id                     45416 non-null  str
 9   original_language      45405 non-null  str
 10  original_title         45416 non-null  str
 11  overview               44464 non-null  str
 12  popularity             45413 non-null  object
 13  poster_path            45035 non-null  str
 14  production_companies   45413 non-null  str
 15  production_countries   45413 non-null  str
 16  release_date           45332 non-null  str
 17  revenue                45413 non-null  float64
 18  runtime                45158 non-null  float64
 19  spoken_languages       45413 non-null  str
 20  status                 45332 non-null  str
 21  video                  45413 non-null  object
 22  vote_average           45413 non-null  float64
 23  vote_count             45413 non-null  float64
 24  keywords               45416 non-null  str
dtypes: float64(4), object(2), str(19)
memory usage: 9.0+ MB

In [310]:
selected_features = ['title','keywords','genres','original_language']

In [311]:
X = df[selected_features]

Convert language code to full form for better understanding

In [312]:
import pycountry
lang = X['original_language'].unique()
print(lang)

def get_lang(code):
    if not isinstance(code, str) or len(str(code).strip()) == 0:
        return "Unknown Language"
        
    try:
        clean_code = code.strip().lower() 
        language = pycountry.languages.get(alpha_2=clean_code) or pycountry.languages.get(alpha_3=clean_code)
        return language.name if language else "Unknown Language"
    except LookupError:
        return "Unknown Language"
X['original_language'] = X['original_language'].apply(get_lang)

lang = X['original_language'].unique()
print(lang)

<StringArray>
['en', 'fr', 'zh', 'it', 'fa', 'nl', 'de', 'cn', 'ar', 'es', 'ru', 'sv', 'ja',
 'ko', 'sr', 'bn', 'he', 'pt', 'wo', 'ro', 'hu', 'cy', 'vi', 'cs', 'da', 'no',
 'nb', 'pl', 'el', 'sh', 'xx', 'mk', 'bo', 'ca', 'fi', 'th', 'sk', 'bs', 'hi',
 'tr', 'is', 'ps', 'ab', 'eo', 'ka', 'mn', 'bm', 'zu', 'uk', 'af', 'la', 'et',
 'ku', 'fy', 'lv', 'ta', 'sl', 'tl', 'ur', 'rw', 'id', 'bg', 'mr', 'lt', 'kk',
 'ms', 'sq',  nan, 'qu', 'te', 'am', 'jv', 'tg', 'ml', 'hr', 'lo', 'ay', 'kn',
 'eu', 'ne', 'pa', 'ky', 'gl', 'uz', 'sm', 'mt', 'hy', 'iu', 'lb', 'si']
Length: 90, dtype: str
<StringArray>
[               'English',                 'French',                'Chinese',
                'Italian',                'Persian',                  'Dutch',
                 'German',       'Unknown Language',                 'Arabic',
                'Spanish',                'Russian',                'Swedish',
               'Japanese',                 'Korean',                'Serbian',
                'Bengali',                 'Hebrew',             'Portuguese',
                  'Wolof',               'Romanian',              'Hungarian',
                  'Welsh',             'Vietnamese',                  'Czech',
                 'Danish',              'Norwegian',       'Norwegian Bokmål',
                 'Polish',   'Modern Greek (1453-)',         'Serbo-Croatian',
             'Macedonian',                'Tibetan',                'Catalan',
                'Finnish',                   'Thai',                 'Slovak',
                'Bosnian',                  'Hindi',                'Turkish',
              'Icelandic',                 'Pushto',              'Abkhazian',
              'Esperanto',               'Georgian',              'Mongolian',
                'Bambara',                   'Zulu',              'Ukrainian',
              'Afrikaans',                  'Latin',               'Estonian',
                'Kurdish',        'Western Frisian',                'Latvian',
                  'Tamil',              'Slovenian',                'Tagalog',
                   'Urdu',            'Kinyarwanda',             'Indonesian',
              'Bulgarian',                'Marathi',             'Lithuanian',
                 'Kazakh',  'Malay (macrolanguage)',               'Albanian',
                'Quechua',                 'Telugu',                'Amharic',
               'Javanese',                  'Tajik',              'Malayalam',
               'Croatian',                    'Lao',                 'Aymara',
                'Kannada',                 'Basque', 'Nepali (macrolanguage)',
                'Panjabi',                'Kirghiz',               'Galician',
                  'Uzbek',                 'Samoan',                'Maltese',
               'Armenian',              'Inuktitut',          'Luxembourgish',
                'Sinhala']
Length: 88, dtype: str

In [313]:
X.head()

,title,keywords,genres,original_language
0,Toy Story,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",English
1,Jumanji,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",English
2,Grumpier Old Men,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",English
3,Waiting to Exhale,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",English
4,Father of the Bride Part II,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'id': 35, 'name': 'Comedy'}]",English

In [314]:
def get_names(keywordList):
    if pd.isna(keywordList):
        return []
    if isinstance(keywordList,str):
        try:
            keywordList = ast.literal_eval(keywordList)
        except (ValueError, SyntaxError):
            return [] 
    if isinstance(keywordList, list):
            return [i['name'] for i in keywordList if isinstance(i, dict) and 'name' in i]

    return []



X['keywords'] = X['keywords'].apply(get_names)
X['genres']=X['genres'].apply(get_names)

In [315]:
X.head()

,title,keywords,genres,original_language
0,Toy Story,"[jealousy, toy, boy, friendship, friends, riva...","[Animation, Comedy, Family]",English
1,Jumanji,"[board game, disappearance, based on children'...","[Adventure, Fantasy, Family]",English
2,Grumpier Old Men,"[fishing, best friend, duringcreditsstinger, o...","[Romance, Comedy]",English
3,Waiting to Exhale,"[based on novel, interracial relationship, sin...","[Comedy, Drama, Romance]",English
4,Father of the Bride Part II,"[baby, midlife crisis, confidence, aging, daug...",[Comedy],English

In [316]:
# Replacing the null valuess with null string
for feature in selected_features:
    X[feature] = X[feature].fillna('')
X['keywords_str'] = X['keywords'].apply(lambda x: ' '.join(x))
X['genres_str'] = X['genres'].apply(lambda x: ' '.join(x))

In [317]:
# combining all the 5 selected features
combined_features = X['title'] + ' ' + X['keywords_str'] + ' ' + X['genres_str'] + ' ' + X['original_language'] 
combined_features

0        Toy Story jealousy toy boy friendship friends ...
1        Jumanji board game disappearance based on chil...
2        Grumpier Old Men fishing best friend duringcre...
3        Waiting to Exhale based on novel interracial r...
4        Father of the Bride Part II baby midlife crisi...
                               ...
46477              Subdue tragic love Drama Family Persian
46478    Century of Birthing artist play pinoy Drama Ta...
46479              Betrayal  Action Drama Thriller English
46480                           Satan Triumphant   English
46481                                   Queerama   English
Length: 45416, dtype: str

In [318]:
vectorizer = TfidfVectorizer()

feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 479286 stored elements and shape (45416, 28774)>
  Coords	Values
  (0, 25953)	0.7725048404010462
  (0, 24294)	0.13558465329866906
  (0, 13106)	0.16724654310943468
  (0, 3458)	0.3056586290779923
  (0, 9767)	0.14178142228937016
  (0, 9766)	0.15669257983917947
  (0, 21314)	0.1794803973690295
  (0, 17512)	0.1961042287260832
  (0, 7481)	0.1961042287260832
  (0, 17484)	0.12160321158464439
  (0, 5423)	0.20084992687692343
  (0, 25738)	0.11721680446129058
  (0, 14682)	0.12679899488889965
  (0, 1230)	0.10773175598945631
  (0, 5422)	0.058104277577422245
  (0, 8865)	0.09232503538938516
  (0, 8267)	0.03494330029494744
  (1, 17484)	0.17745546892022937
  (1, 8865)	0.13472984993242543
  (1, 8267)	0.05099273003282515
  (1, 13378)	0.41898784101081377
  (1, 3176)	0.30519644316097355
  (1, 10010)	0.22620989223863175
  (1, 7181)	0.28234572707814815
  (1, 2371)	0.16255061530871598
  :	:
  (45410, 21372)	0.6615369680937159
  (45411, 8865)	0.2185844263075174
  (45411, 7590)	0.11126592627417922
  (45411, 15030)	0.25664658213349795
  (45411, 19043)	0.43685917070752844
  (45411, 25993)	0.4701607360815274
  (45411, 24469)	0.6797618857521823
  (45412, 7590)	0.08989216054818171
  (45412, 17975)	0.14811916785699383
  (45412, 4567)	0.32167546792604335
  (45412, 1637)	0.3214181669387494
  (45412, 19429)	0.30959493026146284
  (45412, 19318)	0.4297966623756458
  (45412, 24974)	0.4254645721121871
  (45412, 2936)	0.5491821855506382
  (45413, 8267)	0.1601334540514678
  (45413, 7590)	0.21536771749347894
  (45413, 2762)	0.8345374044148793
  (45413, 549)	0.3486207058420542
  (45413, 25547)	0.3316397853784427
  (45414, 8267)	0.09883461090261689
  (45414, 22033)	0.5751064879610261
  (45414, 26207)	0.8120863545170935
  (45415, 8267)	0.12081310517577587
  (45415, 20348)	0.9926752709812946

In [ ]:
# getting the similarity scores using cosine similarity
similarity = cosine_similarity(feature_vectors, feature_vectors)